### ISSUE TITLE
Steps forward

### ISSUE THREAD

**Issue by 4ndh4k** [bevplus/bevplus-v2#5]
# Milestone 1: Simple warehouse management 
A first part of the system to allow manual management of stock. In order to enable that we need to implement the simplest version of the supporting entities.

## Main components
backend - runs on server
webadmin - runs in browser, hosted in bucket or on the server
 
## Main entities in the system

- [ ] User - actor in the system, has a set of permissions/roles that allows him to act in the system
- [ ] Supplier - an entity that owns products
- [ ] Product - a logical group of product variants that share the same specs
- [ ] ProductVariant - a particular version of product,  has a SKU
- [x] Warehouse - represents a location where product variants are stored (as stockItems)
- [x] StockItem - keeps track of how many of a certain productVariant warehouse has
- [x] StockMovement - an entity that describes change in stockItem, how it changed and why

## Definitions:
An user can belong/have access of one or more suppliers
A supplier has users and products
A product has at least one product variant 
A product belongs to exactly one supplier
A product variant belongs to one product 
A warehouse can store any product variant

## Functions/Actions
When a user logs in, depending on permissions, a user can:

- [ ] Can list/create/edit users
- [ ] Can invite users to supplier
- [ ] Can list/edit suppliers
- [ ] Can list/create/edit warehouses
- [ ] Can list/create/edit product and product variants

## Initial steps

- [ ] Setup the monorepo with the main components
- [ ] Setup a stage environment (stage is a environment that mimics a production setup as close as possible but is smaller/less expensive (in previous version it was called 'test') so that we can verify functionality
- [ ] Add user entity to system and verify login/logout
- [ ] Install a very simple webadmin and backend on stage to verify everything works

## Iterative steps
Add simplest versions of each entity to verify their interactions, and define a UI structure to manipulate the crucial data
Add/adapt entities and UI to hold additional data, not necessary for the system but for the users of the system.
